# Generated by Django 5.2.4 on 2025-09-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_add_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
