# Generated by Django 5.2.4 on 2025-08-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_classlevel_subject_studentclassenrollment_and_more'),
        ('marksheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='examtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marksheet.examtype'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='classlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.classlevel'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subject'),
        ),
    ]
