# Generated by Django 5.2.4 on 2025-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0002_marksheet_examtype_alter_marksheet_classlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
