# Generated by Django 5.2.4 on 2025-09-19 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0004_classparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classparticipation',
            name='mark',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
