# Generated by Django 5.2.4 on 2025-07-14 17:32

import assignment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_classlevel_subject_studentclassenrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assignment', models.TextField()),
                ('deadline', models.DateField(default=assignment.models.default_deadline)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.classlevel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
