# Generated by Django 5.2.4 on 2025-07-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_classlevel_subject_studentclassenrollment_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='classlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.classlevel'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='present', max_length=55),
        ),
    ]
