# Generated by Django 5.2.4 on 2025-07-13 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_classlevel_subject_studentclassenrollment_and_more'),
        ('attendance', '0002_rename_user_attendance_student_attendance_classlevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classlevel', 'date')},
        ),
    ]
