# Generated by Django 5.2.4 on 2025-07-21 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_authorizeddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizeddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
